### ISSUE TITLE
Remove illuminate/support dependency

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/yaml-front-matter#10]

**Comment by Arcesilas** [comment]
Hi,

Done it on a fork. To keep using array "dot notation" data access, I use dflydev/dflydev-dot-access-data. What do you think?

**Comment by sebastiandedeyne** [comment]
Hmm would rather have 0 deps. Kind of forgot about this feature before creating this issue. Is it a lot of code in illuminate/support to take over and attribute too?

**Comment by Arcesilas** [comment]
It's not so much code, it's just a shame to rewrite what already exists.

I think it's possible to not add the feature and suggest a dependency to Illuminate/Support (or dflydev-dot-access-data, which I pesonnaly prefer, because it means less code) to provide with the dot notation feature.
If the feature is provided with Illuminate/Support or dflydev-dot-access-data, then YamlFrontMatter would just allow dot notation to access front matter, transparently.

**Comment by Arcesilas** [comment]
So, here are different possible scenarios:
- drop the dot notation feature: user can still use `Arr::get()` on `$document->matter()` array
- drop the dot notation feature, but check if `Illuminate\Support\Arr` exists (and I like the idea to check if dflydev-dot-access-data also exists)
- completely insert the dot notation in the `Document::matter()` method (reinvent the wheel, even if it's a copy/paste of already existing code)
- let the user extend the Document class to implement the dot notation of their choice (use Arr::get(), dflydev-dot-access-data, or anything else). We may provide with one or two classes that work out of the box.

The 3rd one is the most concise for such a small library, even if I don't like the idea of "hard coding" portions of code that exist as a library.
What do you think?

**Comment by sebastiandedeyne** [comment]
Thanks for your research here. I've decided to leave everything as is. The only solution I like is dropping the dot notation feature, but that would be a breaking change. I'll do that when I release the next major version.
