### ISSUE TITLE
Front matter is not detected when it is the only thing the file contains.

### ISSUE THREAD

**Issue by randohinn** [spatie/yaml-front-matter#8]
In cases, such as with files like this

```
---
name:"Fill me up"
----
```
where front-matter is the only thing that the file currently contains, said front-matter is not detected **at all**.  If you add even as much as an empty line at the end of the file:
```
---
name:"Fill me up"
----

```
front-matter instantly gets recognized. I believe that this is a bug and should be resolved. Useful when building, lets say a file-based CMS thingy...

**Comment by Arcesilas** [comment]
What if you use 3 dashes instead of 4 ones?
[        $pattern = '/[\s\r\n]---[\s\r\n]/s';](https://github.com/spatie/yaml-front-matter/blob/6b9a6666a2c3d6b0dd4c69f4a71328d98ad18bf0/src/YamlFrontMatter.php#L11)

**Comment by sebastiandedeyne** [comment]
Hi,

I added a test for this and it seems to pass. Are you sure nothing else is wrong? You seem to have an extra `-` on the bottom line in your example, maybe that's breaking the parser?

https://github.com/spatie/yaml-front-matter/commit/12f6c3bffc75b38fd06a1d822961d57b116c21f1

**Comment by Arcesilas** [comment]
While writing tests for #9 I figured out that there needs to be a white character after the front matter closing dashes `---`

`"---\nfoo: bar\n---"` does not pass the test, whereas `"---\nfoo: bar\n---\n"` does.

This is because of the pattern [`$pattern = '/[\s\r\n]---[\s\r\n]/s';`](https://github.com/spatie/yaml-front-matter/blob/8892c568344191d7195f85ce8d617f2355347a40/src/YamlFrontMatter.php#L11) which makes sense.

The pattern should check whether there is a line break before the body, of if the 3 dashes are at the end of the string.

**Comment by sebastiandedeyne** [comment]
Nice catch, would be a nice-to-have to have this fixed though. Do you have any idea how we can solve this? Update the regex?

**Comment by Arcesilas** [comment]
Here's how I've done it in my (own) package: https://github.com/Arcesilas/yaml-front-matter/blob/develop/src/Document.php
